version: '3'
services:
  app:
    image: ${DOCKER_IMG_NAME}:${COMMIT_HASH}
    ports:
      - "3000:3000"
    volumes:
      - "~/envs/.env:/usr/src/app/.env"
      - "~/envs/ca_bundle.crt:/usr/src/app/ca_bundle.crt"
      - "~/envs/certificate.crt:/usr/src/app/certificate.crt"
      - "~/envs/private.key:/usr/src/app/private.key"
      - "/var/log/logs.log:/usr/src/app/logs.log"

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    ports:
      - 8090:8080