//
//  ProfilePresenterTests.swift
//  Layover
//
//  Created by 김인환 on 12/12/23.
//  Copyright (c) 2023 CodeBomber. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Layover
import XCTest

final class ProfilePresenterTests: XCTestCase {
    // MARK: Subject under test

    var sut: ProfilePresenter!

    typealias Models = ProfileModels

    // MARK: - Test lifecycle

    override func setUp() {
        super.setUp()
        setupProfilePresenter()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: - Test setup

    func setupProfilePresenter() {
        sut = ProfilePresenter()
    }

    // MARK: - Test doubles

    final class ProfileDisplayLogicSpy: ProfileDisplayLogic {
        var displayProfileDidCalled = false
        var displayProfileViewModel: Models.FetchProfile.ViewModel!
        var displayMorePostsCalled = false
        var displayMorePostsViewModel: Models.FetchMorePosts.ViewModel!
        var routeToPostDetailCalled = false

        func displayProfile(viewModel: Models.FetchProfile.ViewModel) {
            displayProfileDidCalled = true
            displayProfileViewModel = viewModel
        }

        func displayMorePosts(viewModel: Models.FetchMorePosts.ViewModel) {
            displayMorePostsCalled = true
            displayMorePostsViewModel = viewModel
        }

        func routeToPostDetail(viewModel: Models.ShowPostDetail.ViewModel) {
            routeToPostDetailCalled = true
        }
    }

    // MARK: - Tests

    func test_presentProfile을_호출하면_displayProfile를_호출하고_올바른_데이터를_전달한다() {
        // arrange
        let spy = ProfileDisplayLogicSpy()
        sut.viewController = spy
        let response = Models.FetchProfile.Response(userProfile: ProfileModels.Profile(username: Seeds.Members.getMember1.username,
                                                                                       introduce: Seeds.Members.getMember1.introduce,
                                                                                       profileImageData: Seeds.sampleImageData),
                                                    posts: [.init(id: Seeds.Posts.post1.board.identifier,

                                                                  thumbnailImageData: Seeds.sampleImageData)])
        // act
        sut.presentProfile(with: response)

        // assert
        XCTAssertTrue(spy.displayProfileDidCalled, "presentProfile은 displayProfile을 호출하지 못했다")
        XCTAssertEqual(spy.displayProfileViewModel.userProfile.username, Seeds.Members.getMember1.username, "presentprofile은 올바른 데이터를 뷰에 전달하지 못했다")
        XCTAssertEqual(spy.displayProfileViewModel.userProfile.introduce, Seeds.Members.getMember1.introduce, "presentprofile은 올바른 데이터를 뷰에 전달하지 못했다")
        XCTAssertEqual(spy.displayProfileViewModel.userProfile.profileImageData, Seeds.sampleImageData, "presentprofile은 올바른 데이터를 뷰에 전달하지 못했다")
        XCTAssertEqual(spy.displayProfileViewModel.posts.count, 1, "presentprofile은 올바른 데이터 갯수를 뷰에 전달하지 못했다")
        XCTAssertEqual(spy.displayProfileViewModel.posts.first?.id, Seeds.Posts.post1.board.identifier, "presentprofile은 올바른 데이터를 뷰에 전달하지 못했다")
        XCTAssertEqual(spy.displayProfileViewModel.posts.first?.thumbnailImageData, Seeds.sampleImageData, "presentprofile은 올바른 데이터를 뷰에 전달하지 못했다")
    }

    func test_presentMorePosts을_호출하면_displayMorePosts를_호출하고_올바른_데이터를_전달한다() {
        // arrange
        let spy = ProfileDisplayLogicSpy()
        sut.viewController = spy

        // act
        let response = Models.FetchMorePosts.Response(posts: [.init(id: Seeds.Posts.post1.board.identifier,
                                                                     thumbnailImageData: Seeds.sampleImageData)])
        sut.presentMorePosts(with: response)

        // assert
        XCTAssertTrue(spy.displayMorePostsCalled, "presentMorePosts은 displayMorePosts을 호출하지 못했다")
        XCTAssertEqual(spy.displayMorePostsViewModel.posts.count, 1, "presentMorePosts은 올바른 데이터 갯수를 뷰에 전달하지 못했다")
        XCTAssertEqual(spy.displayMorePostsViewModel.posts.first?.id, Seeds.Posts.post1.board.identifier, "presentMorePosts은 올바른 데이터를 뷰에 전달하지 못했다")
        XCTAssertEqual(spy.displayMorePostsViewModel.posts.first?.thumbnailImageData, Seeds.sampleImageData, "presentMorePosts은 올바른 데이터를 뷰에 전달하지 못했다")
    }

    func test_presentPostDetail을_호출하면_routeToPostDetail을_호출한다() {
        // arrange
        let spy = ProfileDisplayLogicSpy()
        sut.viewController = spy

        // act
        sut.presentPostDetail(with: .init())

        // assert
        XCTAssertTrue(spy.routeToPostDetailCalled, "presentPostDetail은 routeToPostDetail을 호출하지 못했다")
    }
}
