////
////  ProfilePresenterTests.swift
////  Layover
////
////  Created by 김인환 on 12/12/23.
////  Copyright (c) 2023 CodeBomber. All rights reserved.
////
////  This file was generated by the Clean Swift Xcode Templates so
////  you can apply clean architecture to your iOS and Mac projects,
////  see http://clean-swift.com
////
//
//@testable import Layover
//import XCTest
//
//class ProfilePresenterTests: XCTestCase {
//    // MARK: Subject under test
//
//    var sut: ProfilePresenter!
//
//    // MARK: - Test lifecycle
//
//    override func setUp() {
//        super.setUp()
//        setupProfilePresenter()
//    }
//
//    override func tearDown() {
//        super.tearDown()
//    }
//
//    // MARK: - Test setup
//
//    func setupProfilePresenter() {
//        sut = ProfilePresenter()
//    }
//
//    // MARK: - Test doubles
//
//    class ProfileDisplayLogicSpy: ProfileDisplayLogic {
//        var displaySomethingCalled = false
//
//        func displaySomething(viewModel: Profile.Something.ViewModel) {
//          displaySomethingCalled = true
//        }
//    }
//
//    // MARK: - Tests
//
//    func testPresentSomething() {
//        // Given
//        let spy = ProfileDisplayLogicSpy()
//        sut.viewController = spy
//        let response = Profile.Something.Response()
//
//        // When
//        sut.presentSomething(response: response)
//
//        // Then
//        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//    }
//}
