//
//  SettingWorker.swift
//  Layover
//
//  Created by 김인환 on 12/6/23.
//  Copyright (c) 2023 CodeBomber. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol SettingWorkerProtocol {
    func versionNumber() -> String?
}

final class SettingWorker: SettingWorkerProtocol {

    // MARK: - Methods

    func versionNumber() -> String? {
        System.versionNumber()
    }
}
