//
//  SettingInteractor.swift
//  Layover
//
//  Created by 김인환 on 12/6/23.
//  Copyright (c) 2023 CodeBomber. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingBusinessLogic {
    func performTableViewConfigure(request: SettingModels.ConfigureTableView.Request)
}

protocol SettingDataStore {

}

final class SettingInteractor: SettingBusinessLogic, SettingDataStore {

    // MARK: - Properties

    typealias Models = SettingModels
    var presenter: SettingPresentationLogic?
    var worker: SettingWorkerProtocol?

    func performTableViewConfigure(request: Models.ConfigureTableView.Request) {
        let response = Models.ConfigureTableView.Response(versionNumber: worker?.versionNumber() ?? "")
        presenter?.presentTableView(with: response)
    }
}
