////
////  EditProfilePresenterTests.swift
////  Layover
////
////  Created by 김인환 on 12/13/23.
////  Copyright (c) 2023 CodeBomber. All rights reserved.
////
////  This file was generated by the Clean Swift Xcode Templates so
////  you can apply clean architecture to your iOS and Mac projects,
////  see http://clean-swift.com
////
//
//@testable import Layover
//import XCTest
//
//class EditProfilePresenterTests: XCTestCase {
//    // MARK: Subject under test
//
//    var sut: EditProfilePresenter!
//
//    // MARK: - Test lifecycle
//
//    override func setUp() {
//        super.setUp()
//        setupEditProfilePresenter()
//    }
//
//    override func tearDown() {
//        super.tearDown()
//    }
//
//    // MARK: - Test setup
//
//    func setupEditProfilePresenter() {
//        sut = EditProfilePresenter()
//    }
//
//    // MARK: - Test doubles
//
//    class EditProfileDisplayLogicSpy: EditProfileDisplayLogic {
//        var displaySomethingCalled = false
//
//        func displaySomething(viewModel: EditProfile.Something.ViewModel) {
//          displaySomethingCalled = true
//        }
//    }
//
//    // MARK: - Tests
//
//    func testPresentSomething() {
//        // Given
//        let spy = EditProfileDisplayLogicSpy()
//        sut.viewController = spy
//        let response = EditProfile.Something.Response()
//
//        // When
//        sut.presentSomething(response: response)
//
//        // Then
//        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//    }
//}
