//
//  SignUpWorkerTests.swift
//  Layover
//
//  Created by 김인환 on 1/6/24.
//  Copyright (c) 2024 CodeBomber. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Layover
import XCTest

class SignUpWorkerTests: XCTestCase
{
    // MARK: Subject under test
  
    var sut: SignUpWorker!
  
    // MARK: - Test lifecycle
  
    override func setUp() {
        super.setUp()
        setupSignUpWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: - Test setup
  
    func setupSignUpWorker() {
        sut = SignUpWorker()
    }

    // MARK: - Test doubles

    // MARK: - Tests
  
    func testSomething() {
        // Given

        // When

        // Then
    }
}
