////
////  SignUpPresenterTests.swift
////  Layover
////
////  Created by 김인환 on 1/6/24.
////  Copyright (c) 2024 CodeBomber. All rights reserved.
////
////  This file was generated by the Clean Swift Xcode Templates so
////  you can apply clean architecture to your iOS and Mac projects,
////  see http://clean-swift.com
////
//
//@testable import Layover
//import XCTest
//
//class SignUpPresenterTests: XCTestCase {
//    // MARK: Subject under test
//
//    var sut: SignUpPresenter!
//
//    // MARK: - Test lifecycle
//
//    override func setUp() {
//        super.setUp()
//        setupSignUpPresenter()
//    }
//
//    override func tearDown() {
//        super.tearDown()
//    }
//
//    // MARK: - Test setup
//
//    func setupSignUpPresenter() {
//        sut = SignUpPresenter()
//    }
//
//    // MARK: - Test doubles
//
//    class SignUpDisplayLogicSpy: SignUpDisplayLogic {
//        var displaySomethingCalled = false
//
//        func displaySomething(viewModel: SignUp.Something.ViewModel) {
//          displaySomethingCalled = true
//        }
//    }
//
//    // MARK: - Tests
//
//    func testPresentSomething() {
//        // Given
//        let spy = SignUpDisplayLogicSpy()
//        sut.viewController = spy
//        let response = SignUp.Something.Response()
//
//        // When
//        sut.presentSomething(response: response)
//
//        // Then
//        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//    }
//}
