//
//  TagPlayListInteractorTests.swift
//  Layover
//
//  Created by 김인환 on 12/11/23.
//  Copyright (c) 2023 CodeBomber. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Layover
import XCTest

final class TagPlayListInteractorTests: XCTestCase {
    // MARK: Subject under test

    var sut: TagPlayListInteractor!

    // MARK: Properties

    typealias Models = TagPlayListModels

    // MARK: - Test lifecycle

    override func setUp() {
        super.setUp()
        setupTagPlayListInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: - Test setup

    func setupTagPlayListInteractor() {
        sut = TagPlayListInteractor()
        sut.titleTag = "testTitleTag"
        sut.worker = MockTagPlayListWorker()
    }

    // MARK: - Test doubles

    final class TagPlayListPresentationLogicSpy: TagPlayListPresentationLogic {
        var presentTitleTagCalled = false
        var presentTitleTagResponse: Models.FetchTitleTag.Response!
        var presentPlayListCalled = false
        var presentPlayListResponse: Models.FetchPosts.Response!
        var presentMorePlayListCalled = false
        var presentMorePlayListResponse: Models.FetchMorePosts.Response!
        var presentPostsDetailCalled = false

        func presentTitleTag(response: Models.FetchTitleTag.Response) {
            presentTitleTagCalled = true
            presentTitleTagResponse = response
        }

        func presentPlayList(response: Models.FetchPosts.Response) {
            presentPlayListCalled = true
            presentPlayListResponse = response
        }

        func presentMorePlayList(response: Models.FetchMorePosts.Response) {
            presentMorePlayListCalled = true
            presentMorePlayListResponse = response
        }

        func presentPostsDetail(response: Models.ShowPostsDetail.Response) {
            presentPostsDetailCalled = true
        }


    }

    // MARK: - Tests

    func test_setTitleTag를_호출하면_presenter의_presentTitleTag를_호출한다() {
        // Arrange
        let spy = TagPlayListPresentationLogicSpy()
        sut.presenter = spy
        sut.titleTag = "testTitleTag"
        let request = Models.FetchTitleTag.Request()

        // Act
        sut.setTitleTag(request: request)

        // Assert
        XCTAssertTrue(spy.presentTitleTagCalled, "setTitleTag()가 presenter의 presentTitleTag()를 호출했다.")
        XCTAssertEqual(sut.titleTag, spy.presentTitleTagResponse.titleTag, "setTitleTag()가 presenter에게 자신의 titleTag를 전달했다.")
    }

    func test_setTitleTag를_호출하면_presenter에게_자신의_titleTag를_전달한다() {
        // Arrange
        let spy = TagPlayListPresentationLogicSpy()
        sut.presenter = spy
        sut.titleTag = "testTitleTag"
        let request = Models.FetchTitleTag.Request()

        // Act
        sut.setTitleTag(request: request)

        // Assert
        XCTAssertEqual(sut.titleTag, spy.presentTitleTagResponse.titleTag, "setTitleTag()가 presenter에게 자신의 titleTag를 전달했다.")
    }

    func test_fetchPlayList를_호출하면_presenter의_presentPlayList를_호출한다() async {
        // Arrange
        let spy = TagPlayListPresentationLogicSpy()
        sut.presenter = spy
        let request = Models.FetchPosts.Request()

        // Act
        _ = await sut.fetchPlayList(request: request).value

        // Assert
        XCTAssertTrue(spy.presentPlayListCalled, "fetchPlayList()가 presenter의 presentPlayList()를 호출했다.")
    }

    func test_fetchPlayList를_호출하면_presenter의_presentPlayList에_올바른_갯수의_Posts_데이터를_전달한다() async {
        // Arrange
        let spy = TagPlayListPresentationLogicSpy()
        sut.presenter = spy
        let request = Models.FetchPosts.Request()

        // Act
        _ = await sut.fetchPlayList(request: request).value

        // Assert
        XCTAssertEqual(spy.presentPlayListResponse.post.count, 4, "fetchPlayList()가 presenter에게 올바른 갯수의 posts 데이터를 전달했다.")
    }

    func test_fetchPlayList를_호출하면_자신의_posts에_올바른_갯수의_Posts_데이터를_저장한다() async {
        // Arrange
        let spy = TagPlayListPresentationLogicSpy()
        sut.presenter = spy
        let request = Models.FetchPosts.Request()

        // Act
        _ = await sut.fetchPlayList(request: request).value

        // Assert
        XCTAssertEqual(sut.posts.count, 4, "fetchPlayList()가 자신의 posts에 올바른 갯수의 posts 데이터를 저장했다.")
    }

    func test_fetchPlayList를_호출하면_기존에_저장된_posts를_비우고_새로운_Posts_데이터를_저장한다() async {
        // Arrange
        let spy = TagPlayListPresentationLogicSpy()
        sut.presenter = spy
        guard let dummyImageURL = URL(string: "https://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20210831030133473.jpg/melon/quality/90/optimize") else {
            XCTFail("이미지 URL 생성 오류.")
            return
        }

        guard let dummyVideoURL = URL(string: "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8") else {
            XCTFail("비디오 URL 생성 실패")
            return
        }

        let dummyPost = Post(member: Member(identifier: 1,
                                       username: "안유진",
                                       introduce: "난 아이브의 리더~",
                                       profileImageURL: dummyImageURL),
                        board: Board(identifier: 1,
                                     title: "IZONE",
                                     description: "아이즈원",
                                     thumbnailImageURL: dummyImageURL,
                                     videoURL: dummyVideoURL,
                                     latitude: 0.1203931,
                                     longitude: 0.1029382),
                        tag: ["유진", "아이브", "IVE",])

        sut.posts = [dummyPost, dummyPost]
        let request = Models.FetchPosts.Request()

        // Act
        _ = await sut.fetchPlayList(request: request).value

        // Assert
        XCTAssertEqual(sut.posts.count, 4, "fetchPlayList()가 자신의 posts를 비우고, 새로운 posts 데이터를 저장했다.")
    }

    func test_fetchMorePlayList를_호출하면_presenter의_presentMorePlayList를_호출한다() async {
        // Arrange
        let spy = TagPlayListPresentationLogicSpy()
        sut.presenter = spy
        let request = Models.FetchMorePosts.Request()

        // Act
        _ = await sut.fetchMorePlayList(request: request).value

        // Assert
        XCTAssertTrue(spy.presentMorePlayListCalled, "fetchPlayMoreList()가 presenter의 presentMorePlayList()를 호출했다.")
    }

    func test_fetchPlayList_호출_이후_fetchMorePlayList를_호출하면_presenter에게_올바른_갯수의_Posts_데이터를_전달한다() async {
        // Arrange
        let spy = TagPlayListPresentationLogicSpy()
        sut.presenter = spy
        let fetchRequest = Models.FetchPosts.Request()
        let fetchMoreRequest = Models.FetchMorePosts.Request()

        // Act
        _ = await sut.fetchPlayList(request: fetchRequest).value
        _ = await sut.fetchMorePlayList(request: fetchMoreRequest).value

        // Assert
        XCTAssertEqual(spy.presentMorePlayListResponse.post.count, 4, "fetchPlayMoreList()가 presenter에게 올바른 갯수의 posts 데이터를 전달했다.")
    }

    func test_fetchPlayList_호출_이후_fetchMorePlayList를_호출하면_자신의_posts에_올바른_갯수의_Posts_데이터를_저장한다() async {
        // Arrange
        let spy = TagPlayListPresentationLogicSpy()
        sut.presenter = spy
        let fetchRequest = Models.FetchPosts.Request()
        let request = Models.FetchMorePosts.Request()

        // Act
        _ = await sut.fetchPlayList(request: fetchRequest).value
        _ = await sut.fetchMorePlayList(request: request).value

        // Assert
        XCTAssertEqual(sut.posts.count, 8, "fetchPlayMoreList()가 자신의 posts에 올바른 갯수의 posts 데이터를 저장했다.")
    }

    func test_fetchMorePlayList를_호출하다가_더이상_가져온_데이터가_없으면_본인의_post개수를_유지한다() async {
        // Arrange
        let spy = TagPlayListPresentationLogicSpy()
        sut.presenter = spy
        let request = Models.FetchMorePosts.Request()

        // Act
        _ = await sut.fetchMorePlayList(request: request).value
        _ = await sut.fetchMorePlayList(request: request).value
        _ = await sut.fetchMorePlayList(request: request).value

        // Assert
        XCTAssertEqual(sut.posts.count, 8, "fetchPlayMoreList()를 호출하다가 더이상 데이터가 없을 때 자신의 posts를 유지했다.")
    }

    func test_fetchMorePlayList를_호출하다가_더이상_데이터가_없으면_presenter에게_빈_배열을_전달한다() async {
        // Arrange
        let spy = TagPlayListPresentationLogicSpy()
        sut.presenter = spy
        let request = Models.FetchMorePosts.Request()

        // Act
        _ = await sut.fetchMorePlayList(request: request).value
        _ = await sut.fetchMorePlayList(request: request).value
        _ = await sut.fetchMorePlayList(request: request).value

        // Assert
        XCTAssertEqual(spy.presentMorePlayListResponse.post.count, 0, "fetchPlayMoreList()가 presenter에게 빈 배열을 전달했다.")
    }

    func test_fetchMorePlayList를_호출하면_기존_자신의_posts에_새로운_Posts_데이터를_추가하여_저장한다() async {
        // Arrange
        let spy = TagPlayListPresentationLogicSpy()
        sut.presenter = spy

        guard let dummyImageURL = URL(string: "https://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20210831030133473.jpg/melon/quality/90/optimize") else {
            XCTFail("이미지 URL 생성 오류.")
            return
        }

        guard let dummyVideoURL = URL(string: "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8") else {
            XCTFail("비디오 URL 생성 실패")
            return
        }

        let dummyPost = Post(member: Member(identifier: 1,
                                       username: "안유진",
                                       introduce: "난 아이브의 리더~",
                                       profileImageURL: dummyImageURL),
                        board: Board(identifier: 1,
                                     title: "IZONE",
                                     description: "아이즈원",
                                     thumbnailImageURL: dummyImageURL,
                                     videoURL: dummyVideoURL,
                                     latitude: 0.1203931,
                                     longitude: 0.1029382),
                        tag: ["유진", "아이브", "IVE",])

        sut.posts = [dummyPost, dummyPost, dummyPost, dummyPost]
        let request = Models.FetchMorePosts.Request()

        // Act
        _ = await sut.fetchMorePlayList(request: request).value

        // Assert
        XCTAssertEqual(sut.posts.count, 8, "fetchPlayMoreList()가 자신의 posts에 새로운 posts 데이터를 더해서 저장했다.")
    }

    func test_fetchMorePlayList를_호출하다가_다시_fetchPlayList를_호출하면_자신의_posts를_초기화한다() async {
        // Arrange
        let spy = TagPlayListPresentationLogicSpy()
        sut.presenter = spy
        let fetchRequest = Models.FetchPosts.Request()
        let fetchMoreRequest = Models.FetchMorePosts.Request()

        // Act
        _ = await sut.fetchPlayList(request: fetchRequest).value
        _ = await sut.fetchMorePlayList(request: fetchMoreRequest).value
        _ = await sut.fetchMorePlayList(request: fetchMoreRequest).value
        _ = await sut.fetchMorePlayList(request: fetchMoreRequest).value
        _ = await sut.fetchPlayList(request: fetchRequest).value

        // Assert
        XCTAssertEqual(sut.posts.count, 4, "fetchPlayList()가 자신의 posts를 초기화했다.")
    }

    func test_showPostDetail을_호출하면_presenter의_presentPostDetail을_호출한다() {
        // Arrange
        let spy = TagPlayListPresentationLogicSpy()
        sut.presenter = spy
        let request = Models.ShowPostsDetail.Request(startIndex: 0)

        // Act
        sut.showPostsDetail(request: request)

        // Assert
        XCTAssertTrue(spy.presentPostsDetailCalled, "showPostDetail()가 presenter의 presentPostDetail()를 호출했다.")
    }

    func test_showPostDetail을_호출하면_자신의_postPlayStartIndex값을_올바르게_저장한다() {
        // Arrange
        let spy = TagPlayListPresentationLogicSpy()
        sut.presenter = spy
        let request = Models.ShowPostsDetail.Request(startIndex: 7)

        // Act
        sut.showPostsDetail(request: request)

        // Assert
        XCTAssertEqual(sut.postPlayStartIndex, 7, "showPostDetail()가 presenter에게 올바른 startIndex를 전달했다.")
    }
}
