//
//  TagPlayListWorkerTests.swift
//  Layover
//
//  Created by 김인환 on 12/11/23.
//  Copyright (c) 2023 CodeBomber. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Layover
import XCTest

class TagPlayListWorkerTests: XCTestCase
{
    // MARK: Subject under test
  
    var sut: TagPlayListWorker!
  
    // MARK: - Test lifecycle
  
    override func setUp() {
        super.setUp()
        setupTagPlayListWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: - Test setup
  
    func setupTagPlayListWorker() {
        sut = TagPlayListWorker()
    }

    // MARK: - Test doubles

    // MARK: - Tests
  
    func testSomething() {
        // Given

        // When

        // Then
    }
}
