//
//  SettingViewControllerTests.swift
//  Layover
//
//  Created by 김인환 on 12/13/23.
//  Copyright (c) 2023 CodeBomber. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Layover
import XCTest

final class SettingViewControllerTests: XCTestCase {
    // MARK: Subject under test

    var sut: SettingViewController!

    // MARK: - Test lifecycle

    override func setUp() {
        super.setUp()
        setupSettingViewController()
    }

    // MARK: - Test setup

    func setupSettingViewController() {
        sut = SettingViewController()
    }

    // MARK: - Test doubles

    final class SettingBusinessLogicSpy: SettingBusinessLogic {
        var performTableViewConfigureCalled = false
        var performUserLogoutCalled = false
        var performUserWithdrawCalled = false

        func performTableViewConfigure(request: Layover.SettingModels.ConfigureTableView.Request) {
            performTableViewConfigureCalled = true
        }

        func performUserLogout(request: Layover.SettingModels.Logout.Request) {
            performUserLogoutCalled = true
        }

        func performUserWithdraw(request: Layover.SettingModels.Withdraw.Request) -> Task<Bool, Never> {
            performUserWithdrawCalled = true
            return Task {
                true
            }
        }
    }

    // MARK: - Tests

    func test_setUI가_호출되면_interactor의_performTableViewConfigure를_호출한다() {
        // arrange
        let spy = SettingBusinessLogicSpy()
        sut.interactor = spy

        // act
        sut.setUI()

        // assert
        XCTAssertTrue(spy.performTableViewConfigureCalled, "setUI()가 호출되어 performTableViewConfigure() 가 호출되지 않았다")
    }
}
