//
//  HomeViewControllerTests.swift
//  Layover
//
//  Created by 김인환 on 12/4/23.
//  Copyright (c) 2023 CodeBomber. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Layover
import XCTest

final class HomeViewControllerTests: XCTestCase {
    // MARK: Subject under test

    var sut: HomeViewController!
    var window: UIWindow!

    // MARK: - Test lifecycle

    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupHomeViewController()
    }

    override func tearDown() {
        window = nil
        super.tearDown()
    }

    // MARK: - Test setup

    func setupHomeViewController() {
        sut = HomeViewController()
    }

    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }

    // MARK: - Test doubles

    class HomeBusinessLogicSpy: HomeBusinessLogic {
        func fetchPosts(with request: Layover.HomeModels.FetchPosts.Request) -> Task<Bool, Never> {
            return Task { return true }
        }
        
        func fetchThumbnailImageData(with request: Layover.HomeModels.FetchThumbnailImageData.Request) -> Task<Bool, Never> {
            return Task { return true }
        }
        
        func playPosts(with request: Layover.HomeModels.PlayPosts.Request) {
            return
        }
        
        func selectVideo(with request: Layover.HomeModels.SelectVideo.Request) {
            return
        }
        
        func showTagPlayList(with request: Layover.HomeModels.ShowTagPlayList.Request) {
            return
        }
    }

    // MARK: - Tests

}
