//
//  HomePresenterTests.swift
//  Layover
//
//  Created by 김인환 on 12/4/23.
//  Copyright (c) 2023 CodeBomber. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Layover
import XCTest

//final class HomePresenterTests: XCTestCase {
//    // MARK: - Subject under test
//    var sut: HomePresenter!
//
//    typealias Models = HomeModels
//
//    // MARK: - Test lifecycle
//
//    override func setUp() {
//        super.setUp()
//        setupHomePresenter()
//    }
//
//    override func tearDown() {
//        super.tearDown()
//    }
//
//    // MARK: - Test setup
//
//    func setupHomePresenter() {
//        sut = HomePresenter()
//    }
//
//    // MARK: - Test doubles
//
//    final class HomeDisplayLogicSpy: HomeDisplayLogic {
//        var displayPostsCalled = false
//        var displayPostsReceivedViewModel: Models.FetchPosts.ViewModel!
//        var displayThumbnailImageCalled = false
//        var displayThumbnailImageReceivedViewModel: Models.FetchThumbnailImageData.ViewModel!
//        var routeToPlaybackCalled = false
//        var routeToTagPlayListCalled = false
//
//        func displayPosts(with viewModel: Layover.HomeModels.FetchPosts.ViewModel) {
//            displayPostsCalled = true
//            displayPostsReceivedViewModel = viewModel
//        }
//        
//        func displayThumbnailImage(with viewModel: Layover.HomeModels.FetchThumbnailImageData.ViewModel) {
//            displayThumbnailImageCalled = true
//            displayThumbnailImageReceivedViewModel = viewModel
//        }
//        
//        func routeToPlayback() {
//            routeToPlaybackCalled = true
//        }
//        
//        func routeToTagPlayList() {
//            routeToTagPlayListCalled = true
//        }
//    }
//
//    // MARK: - Tests
//
//    func test_presentPosts는_데이터를_받아오면_뷰의_displayPosts를_실행한다() {
//        // arrange
//        let spy = HomeDisplayLogicSpy()
//        sut.viewController = spy
//
//        guard let imageURL = URL(string: "https://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20210831030133473.jpg/melon/quality/90/optimize") else {
//            XCTFail("이미지 URL 생성 오류.")
//            return
//        }
//
//        guard let dummyVideoURL = URL(string: "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8") else {
//            XCTFail("비디오 URL 생성 실패")
//            return
//        }
//
//        let post = Post(member: Member(identifier: 1,
//                                       username: "안유진",
//                                       introduce: "난 아이브의 리더~",
//                                       profileImageURL: imageURL),
//                        board: Board(identifier: 1,
//                                     title: "IZONE",
//                                     description: "아이즈원",
//                                     thumbnailImageURL: imageURL,
//                                     videoURL: dummyVideoURL,
//                                     latitude: 0.1203931,
//                                     longitude: 0.1029382),
//                        tag: ["유진", "아이브", "IVE",])
//        let response = Models.FetchPosts.Response(posts: [post])
//
//        // act
//        sut.presentPosts(with: response)
//
//        // assert
//        XCTAssertTrue(spy.displayPostsCalled, "presentPosts는 displayPosts를 실행해서 뷰에게 데이터를 전달했다.")
//    }
//
//    func test_presentPosts는_데이터의_썸네일_이미지_URL이_nil인_경우_뷰에게_해당_데이터를_전달하지_않는다() {
//        // arrange
//        let spy = HomeDisplayLogicSpy()
//        sut.viewController = spy
//
//        guard let imageURL = URL(string: "https://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20210831030133473.jpg/melon/quality/90/optimize") else {
//            XCTFail("이미지 URL 생성 오류.")
//            return
//        }
//
//        guard let dummyVideoURL = URL(string: "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8") else {
//            XCTFail("비디오 URL 생성 실패")
//            return
//        }
//
//        let post = Post(member: Member(identifier: 1,
//                                       username: "안유진",
//                                       introduce: "난 아이브의 리더~",
//                                       profileImageURL: imageURL),
//                        board: Board(identifier: 1,
//                                     title: "IZONE",
//                                     description: "아이즈원",
//                                     thumbnailImageURL: nil, // nil
//                                     videoURL: dummyVideoURL,
//                                     latitude: 0.1203931,
//                                     longitude: 0.1029382),
//                        tag: ["유진", "아이브", "IVE",])
//        let response = Models.FetchPosts.Response(posts: [post])
//
//        // act
//        sut.presentPosts(with: response)
//
//        // assert
//        XCTAssertTrue(spy.displayPostsCalled, "presentPosts는 displayPosts를 실행했다.")
//        XCTAssertEqual(spy.displayPostsReceivedViewModel.displayedPosts.count, 0, "썸네일 이미지 URL이 nil인 데이터는 뷰에게 전달하지 않는다.")
//    }
//
//    func test_presentPosts는_데이터의_비디오_URL이_nil인_경우_뷰에게_해당_데이터를_전달하지_않는다() {
//        // arrange
//        let spy = HomeDisplayLogicSpy()
//        sut.viewController = spy
//
//        guard let imageURL = URL(string: "https://cdnimg.melon.co.kr/resource/image/cds/musicstory/imgUrl20210831030133473.jpg/melon/quality/90/optimize") else {
//            XCTFail("이미지 URL 생성 오류.")
//            return
//        }
//
//        let post = Post(member: Member(identifier: 1,
//                                       username: "안유진",
//                                       introduce: "난 아이브의 리더~",
//                                       profileImageURL: imageURL),
//                        board: Board(identifier: 1,
//                                     title: "IZONE",
//                                     description: "아이즈원",
//                                     thumbnailImageURL: imageURL,
//                                     videoURL: nil, // nil
//                                     latitude: 0.1203931,
//                                     longitude: 0.1029382),
//                        tag: ["유진", "아이브", "IVE",])
//        let response = Models.FetchPosts.Response(posts: [post])
//
//        // act
//        sut.presentPosts(with: response)
//
//        // assert
//        XCTAssertTrue(spy.displayPostsCalled, "presentPosts는 displayPosts를 실행했다.")
//        XCTAssertEqual(spy.displayPostsReceivedViewModel.displayedPosts.count, 0, "비디오 URL이 nil인 데이터는 뷰에게 전달하지 않는다.")
//    }
//
//    func test_presentThumbnailImage는_데이터를_받아오면_뷰의_displayThumbnailImage를_실행한다() {
//        // arrange
//        let spy = HomeDisplayLogicSpy()
//        sut.viewController = spy
//
//        let response = Models.FetchThumbnailImageData.Response(imageData: Data(), indexPath: IndexPath())
//
//        // act
//        sut.presentThumbnailImage(with: response)
//
//        // assert
//        XCTAssertTrue(spy.displayThumbnailImageCalled, "presentThumbnailImage는 displayThumbnailImage를 실행해서 뷰에게 데이터를 전달했다.")
//    }
//
//    func test_presentPlaybackScene은_뷰의_routeToPlayback을_실행한다() {
//        // arrange
//        let spy = HomeDisplayLogicSpy()
//        sut.viewController = spy
//
//        // act
//        sut.presentPlaybackScene(with: Models.PlayPosts.Response())
//
//        // assert
//        XCTAssertTrue(spy.routeToPlaybackCalled, "presentPlaybackScene은 routeToPlayback을 실행했다.")
//    }
//
//    func test_presentTagPlayList는_뷰의_routeToTagPlayList를_실행한다() {
//        // arrange
//        let spy = HomeDisplayLogicSpy()
//        sut.viewController = spy
//
//        // act
//        sut.presentTagPlayList(with: Models.ShowTagPlayList.Response())
//
//        // assert
//        XCTAssertTrue(spy.routeToTagPlayListCalled, "presentTagPlayListScene은 routeToTagPlayList를 실행했다.")
//    }
//
//}
