//
//  HomeViewControllerTests.swift
//  Layover
//
//  Created by 김인환 on 12/4/23.
//  Copyright (c) 2023 CodeBomber. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Layover
import XCTest

// View는 액션이 섞여있기에 가능한 정도 까지만 테스트 작성
final class HomeViewControllerTests: XCTestCase {
    // MARK: Subject under test

    var sut: HomeViewController!
    var window: UIWindow!

    // MARK: - Test lifecycle

    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupHomeViewController()
    }

    override func tearDown() {
        window = nil
        super.tearDown()
    }

    // MARK: - Test setup

    func setupHomeViewController() {
        sut = HomeViewController()
    }

    // MARK: - Test doubles

//    final class HomeBusinessLogicSpy: HomeBusinessLogic {
//        var fetchPostsCalled = false
//        var fetchThumbnailImageDataCalled = false
//        var playPostsCalled = false
//        var selectVideoCalled = false
//        var showTagPlayListCalled = false
//
//        func fetchPosts(with request: Layover.HomeModels.FetchPosts.Request) -> Task<Bool, Never> {
//            fetchPostsCalled = true
//            return Task { return true }
//        }
//        
//        func fetchThumbnailImageData(with request: Layover.HomeModels.FetchThumbnailImageData.Request) -> Task<Bool, Never> {
//            fetchThumbnailImageDataCalled = true
//            return Task { return true }
//        }
//        
//        func playPosts(with request: Layover.HomeModels.PlayPosts.Request) {
//            playPostsCalled = true
//        }
//        
//        func selectVideo(with request: Layover.HomeModels.SelectVideo.Request) {
//            selectVideoCalled = true
//        }
//        
//        func showTagPlayList(with request: Layover.HomeModels.ShowTagPlayList.Request) {
//            showTagPlayListCalled = true
//        }
//    }

    final class HomeRouterSpy: HomeRouter {
        var routeToNextCalled = false
        var routeToEditVideoCalled = false
        var routeToPlaybackCalled = false
        var routeToTagPlayCalled = false

        override func routeToNext() {
            routeToNextCalled = true
        }

        override func routeToEditVideo() {
            routeToEditVideoCalled = true
        }

        override func routeToPlayback() {
            routeToPlaybackCalled = true
        }

        override func routeToTagPlay() {
            routeToTagPlayCalled = true
        }
    }

    // MARK: - Tests

    func test_routeToPlayback_호출시_router의_routeToPlayback을_호출한다() {
        // arrange
        let spy = HomeRouterSpy()
        sut.router = spy

        // act
        sut.routeToPlayback()

        // assert
        XCTAssertTrue(spy.routeToPlaybackCalled, "routeToPlayback 호출 시 router의 routeToPlayback이 호출되었다.")
    }

    func test_routeToTagPlayList_호출시_router의_routeToTagPlay를_호출한다() {
        // arrange
        let spy = HomeRouterSpy()
        sut.router = spy

        // act
        sut.routeToTagPlayList()

        // assert
        XCTAssertTrue(spy.routeToTagPlayCalled, "routeToTagPlayList 호출 시 router의 routeToTagPlay가 호출되었다.")
    }
}
